### ISSUE TITLE
Propose technologies to be used for service

### ISSUE THREAD

**Issue by mariobehling** [fossasia/CommonsNet#3]
What technology/framework etc. should we use for the site?

**Comment by agwisniewska** [comment]
@mariobehling I am thinking about
wordpress -  https://wordpress.org/ and php
MySQL database, 
Javascript/ Jquery to wizard flow, contact form, 
Bootstrap, SASS,

**Comment by mariobehling** [comment]
Please list pros/cons etc.

**Comment by agwisniewska** [comment]
@mariobehling 
## Wordpress ##
- helps to maintain a website in an easy way, make updates, add content etc.
- it enables to add new pages, blog posts, videos quickly and it is not too complicated. 
- many dedicated plugins  can be used to extend features. 
- easy connection to socialmedia as well.  
- Wordpress is also really friendly for SEO. I think it is really important feature to us, because as soon as website will be finished we need to promote it in a most successful way, so a good position in search engines seems to be really important.
- Wordpress is not very well secured, but there are many possibilities, plugins to improve its security and keep control on data

## PHP ##
- it is required if we want to use wordpress. 
- it is not the most friendly language

## MySQL ##
- is used as Wordpress database management system. 
- it is relatively easy to use, 
- it has many online tutorials to learn it and solve problems. 

## Bootstrap ##
- it helps to create website quickly 
- it enables to take care of responsiveness. 
- it enables to choose desired feature from the list and easy adjustment to needs
- the UI is quite popular, recognizable and could be considered as non original...

## SASS ##
- it supports responsiveness
- it enables to avoid adding repetitive styles 
- in comparison to simple css it requires some time to learn it.

## JQuery ##
- it is quite easy-to-understand and friendly
- it has huge libraries
- it contains wide range of plugins to specific needs
- it  supports AJAX
- it easier to use than JavaScript.

**Comment by mariobehling** [comment]
Thanks a lot. I think we are all mostly aware of the technologies. The question is rather, what is the pro or con of using these technologies for this project, rather than using other technologies.

**Comment by agwisniewska** [comment]
@mariobehling
I am simply familiar with JQuery, JavaScript and Bootstrap. So it helps me to code faster. 
And we can avoid using wordpress and php on Commonsnet website and create outside blog in wordpress.com like Open Event

**Comment by hongquan** [comment]
If you avoid PHP, which technology will be used for backend? Or you want to use JavaScript for backend as well (NodeJS)?

**Comment by agwisniewska** [comment]
Firstly, I am not sure if I need it. It depends on the fact if we want to have a panel admin. I think it is not absolutely necessary. next if yes, PHP is not friendly to me and I want to avoid it, so I can use Python, which is not so strange to me as PHP. I have written about PHP only if I have to use WordPress. If not - it's not good idea for me to use PHP.

**Comment by agwisniewska** [comment]
I guess that JavaScript - Node JS for backend is good as well.
